version: "3"

volumes:
  staticfiles:
  postgres_data:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - staticfiles:/app/staticfiles/
      - ./backend:/app/backend/
    command: sh -c "sh ./scripts/entrypoint.sh"
    depends_on:
      - db
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - staticfiles:/app/staticfiles/
      - ./frontend/:/app/frontend/
    depends_on:
      - backend
    ports:
      - "80:80"
